MAKEFILE_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
ROOT_DIR := $(MAKEFILE_DIR)..

TARGET = $(ROOT_DIR)/mz1500

CXX ?= /usr/local/bin/g++
SDL_CFLAGS ?= -I/usr/local/include/SDL2 -D_REENTRANT
SDL_LIBS ?= -L/usr/local/lib -lSDL2
GTK2_CFLAGS ?= $(shell pkg-config --cflags gtk+-2.0 2>/dev/null)
GTK2_LIBS ?= $(shell pkg-config --libs gtk+-2.0 2>/dev/null)

CXXFLAGS += -O3 -std=gnu++11 -mvis -mcpu=ultrasparc -mtune=ultrasparc
CXXFLAGS += -D_MZ1500 -D__BIG_ENDIAN__ -D__SOLARIS__
CXXFLAGS += -I$(ROOT_DIR)/src -I$(ROOT_DIR)/src/vm -I$(ROOT_DIR)/src/vm/mz700 -I$(ROOT_DIR)/src/solaris
CXXFLAGS += -include $(ROOT_DIR)/src/solaris/osd_compat.h
CXXFLAGS += $(SDL_CFLAGS) $(GTK2_CFLAGS) -MMD -MP

LDFLAGS += -L/usr/local/lib -Wl,-R,/usr/local/lib -L/usr/openwin/lib -Wl,-R,/usr/openwin/lib
LDLIBS += $(SDL_LIBS) $(GTK2_LIBS) -lX11 -lsocket -lnsl -lm -lpthread

COMMON_SRCS = \
	$(ROOT_DIR)/src/common.cpp \
	$(ROOT_DIR)/src/config.cpp \
	$(ROOT_DIR)/src/fileio.cpp \
	$(ROOT_DIR)/src/fifo.cpp

VM_SRCS = \
	$(ROOT_DIR)/src/vm/and.cpp \
	$(ROOT_DIR)/src/vm/cmu800.cpp \
	$(ROOT_DIR)/src/vm/datarec.cpp \
	$(ROOT_DIR)/src/vm/disk.cpp \
	$(ROOT_DIR)/src/vm/event.cpp \
	$(ROOT_DIR)/src/vm/i8253.cpp \
	$(ROOT_DIR)/src/vm/i8255.cpp \
	$(ROOT_DIR)/src/vm/io.cpp \
	$(ROOT_DIR)/src/vm/mb8877.cpp \
	$(ROOT_DIR)/src/vm/midi.cpp \
	$(ROOT_DIR)/src/vm/mz1p17.cpp \
	$(ROOT_DIR)/src/vm/mz700/cmos.cpp \
	$(ROOT_DIR)/src/vm/mz700/emm.cpp \
	$(ROOT_DIR)/src/vm/mz700/floppy.cpp \
	$(ROOT_DIR)/src/vm/mz700/joystick.cpp \
	$(ROOT_DIR)/src/vm/mz700/kanji.cpp \
	$(ROOT_DIR)/src/vm/mz700/keyboard.cpp \
	$(ROOT_DIR)/src/vm/mz700/memory.cpp \
	$(ROOT_DIR)/src/vm/mz700/mz700.cpp \
	$(ROOT_DIR)/src/vm/mz700/psg.cpp \
	$(ROOT_DIR)/src/vm/mz700/quickdisk.cpp \
	$(ROOT_DIR)/src/vm/mz700/ramfile.cpp \
	$(ROOT_DIR)/src/vm/noise.cpp \
	$(ROOT_DIR)/src/vm/not.cpp \
	$(ROOT_DIR)/src/vm/pcm1bit.cpp \
	$(ROOT_DIR)/src/vm/prnfile.cpp \
	$(ROOT_DIR)/src/vm/sn76489an.cpp \
	$(ROOT_DIR)/src/vm/z80.cpp \
	$(ROOT_DIR)/src/vm/z80pio.cpp \
	$(ROOT_DIR)/src/vm/z80sio.cpp

SOLARIS_SRCS = \
	$(ROOT_DIR)/src/solaris/osd.cpp \
	$(ROOT_DIR)/src/solaris/osd_control.cpp \
	$(ROOT_DIR)/src/solaris/osd_video.cpp \
	$(ROOT_DIR)/src/solaris/solaris_main.cpp

SRCS = $(COMMON_SRCS) $(VM_SRCS) $(SOLARIS_SRCS)
OBJS = $(SRCS:.cpp=.o)
DEPS = $(OBJS:.o=.d)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(LDFLAGS) -o $@ $(OBJS) $(LDFLAGS) $(LDLIBS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(TARGET) $(OBJS) $(DEPS)

-include $(DEPS)
